/* ============================================================
   Notes loader + viewer
   Reads notes/manifest.json (auto-generated by GitHub Action)
   ============================================================ */

let ALL_NOTES = [];
let activeFilter = "all";

const listEl   = document.getElementById("notes-list");
const searchEl = document.getElementById("notes-search");
const filterEl = document.getElementById("notes-filters");
const viewer   = document.getElementById("viewer");
const vTitle   = document.getElementById("viewer-title");
const vBody    = document.getElementById("viewer-body");
const vClose   = document.getElementById("viewer-close");

document.getElementById("year").textContent = new Date().getFullYear();

/* ---- load manifest ---- */
async function loadNotes(){
  try{
    const res = await fetch("notes/manifest.json", {cache:"no-store"});
    if(!res.ok) throw new Error("no manifest");
    const data = await res.json();
    ALL_NOTES = (data.notes || []).sort((a,b)=> (b.modified||"").localeCompare(a.modified||""));
    if(data.generated){
      const d = new Date(data.generated);
      document.getElementById("build-time").textContent =
        d.toLocaleDateString(undefined,{year:"2-digit",month:"short",day:"numeric"});
    }
    buildFilters();
    render();
  }catch(e){
    listEl.innerHTML = `<p class="notes-empty">No notes found yet. Drop a <code>.pdf</code> or <code>.md</code> into the <code>/notes</code> folder and push — they'll appear here automatically.</p>`;
  }
}

/* ---- filter chips by type ---- */
function buildFilters(){
  const types = ["all", ...new Set(ALL_NOTES.map(n=>n.type))];
  filterEl.innerHTML = types.map(t=>
    `<button class="filter-btn ${t==="all"?"active":""}" data-type="${t}">${t}</button>`
  ).join("");
  filterEl.querySelectorAll(".filter-btn").forEach(b=>{
    b.addEventListener("click",()=>{
      activeFilter = b.dataset.type;
      filterEl.querySelectorAll(".filter-btn").forEach(x=>x.classList.remove("active"));
      b.classList.add("active");
      render();
    });
  });
}

/* ---- render list ---- */
function render(){
  const q = searchEl.value.trim().toLowerCase();
  const filtered = ALL_NOTES.filter(n=>{
    const okType = activeFilter==="all" || n.type===activeFilter;
    const okSearch = !q || n.title.toLowerCase().includes(q);
    return okType && okSearch;
  });

  if(!filtered.length){
    listEl.innerHTML = `<p class="notes-empty">No notes match.</p>`;
    return;
  }

  listEl.innerHTML = filtered.map(n=>{
    const meta = [n.modified ? fmtDate(n.modified) : null, n.size].filter(Boolean).join("  ·  ");
    return `<button class="note" data-path="${n.path}" data-type="${n.type}" data-title="${escapeAttr(n.title)}">
      <span class="note-type ${n.type}">${n.type}</span>
      <span class="note-main">
        <span class="note-title">${escapeHtml(n.title)}</span>
        <span class="note-meta">${meta}</span>
      </span>
      <span class="note-arrow">→</span>
    </button>`;
  }).join("");

  listEl.querySelectorAll(".note").forEach(el=>{
    el.addEventListener("click",()=>openNote(el.dataset.path, el.dataset.type, el.dataset.title));
  });
}

/* ---- open a note in the viewer ---- */
async function openNote(path, type, title){
  vTitle.textContent = "~/notes/" + title;
  viewer.classList.add("open");
  viewer.setAttribute("aria-hidden","false");
  document.body.style.overflow="hidden";

  if(type==="pdf"){
    vBody.innerHTML = `<iframe src="${path}#view=FitH" title="${escapeAttr(title)}"></iframe>
      <p style="margin-top:16px;font-size:13px;color:var(--text-faint)">
      Trouble viewing? <a href="${path}" target="_blank" rel="noopener">Open PDF in new tab ↗</a></p>`;
    return;
  }

  // markdown
  vBody.innerHTML = `<p style="color:var(--text-faint)">loading…</p>`;
  try{
    const res = await fetch(path,{cache:"no-store"});
    const md = await res.text();
    vBody.innerHTML = window.marked ? marked.parse(md) : `<pre>${escapeHtml(md)}</pre>`;
    vBody.scrollTop = 0;
  }catch(e){
    vBody.innerHTML = `<p>Couldn't load this note. <a href="${path}" target="_blank">Open raw ↗</a></p>`;
  }
}

function closeViewer(){
  viewer.classList.remove("open");
  viewer.setAttribute("aria-hidden","true");
  document.body.style.overflow="";
  vBody.innerHTML="";
}
vClose.addEventListener("click",closeViewer);
viewer.addEventListener("click",e=>{ if(e.target===viewer) closeViewer(); });
document.addEventListener("keydown",e=>{ if(e.key==="Escape") closeViewer(); });

searchEl.addEventListener("input",render);

/* ---- helpers ---- */
function fmtDate(iso){
  try{ return new Date(iso).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}); }
  catch{ return ""; }
}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function escapeAttr(s){return escapeHtml(s).replace(/"/g,"&quot;");}

loadNotes();
