/* ============================================================
   Notes loader + viewer
   Reads notes/manifest.json (auto-generated by GitHub Action)
   ============================================================ */

let ALL_NOTES = [];
let activeFilter = "all";

const listEl   = document.getElementById("notes-list");
const searchEl = document.getElementById("notes-search");
const filterEl = document.getElementById("notes-filters");
const viewer   = document.getElementById("viewer");
const vTitle   = document.getElementById("viewer-title");
const vBody    = document.getElementById("viewer-body");
const vClose   = document.getElementById("viewer-close");

document.getElementById("year").textContent = new Date().getFullYear();

/* ---- load manifest ---- */
async function loadNotes(){
  try{
    const res = await fetch("notes/manifest.json", {cache:"no-store"});
    if(!res.ok) throw new Error("no manifest");
    const data = await res.json();
    ALL_NOTES = (data.notes || []).sort((a,b)=> (b.modified||"").localeCompare(a.modified||""));
    if(data.generated){
      const d = new Date(data.generated);
      document.getElementById("build-time").textContent =
        d.toLocaleDateString(undefined,{year:"2-digit",month:"short",day:"numeric"});
    }
    buildFilters();
    render();
  }catch(e){
    listEl.innerHTML = `<p class="notes-empty">No notes found yet. Drop a <code>.pdf</code> or <code>.md</code> into the <code>/notes</code> folder and push — they'll appear here automatically.</p>`;
  }
}

/* ---- filter chips by type ---- */
function buildFilters(){
  const types = ["all", ...new Set(ALL_NOTES.map(n=>n.type))];
  filterEl.innerHTML = types.map(t=>
    `<button class="filter-btn ${t==="all"?"active":""}" data-type="${t}">${t}</button>`
  ).join("");
  filterEl.querySelectorAll(".filter-btn").forEach(b=>{
    b.addEventListener("click",()=>{
      activeFilter = b.dataset.type;
      filterEl.querySelectorAll(".filter-btn").forEach(x=>x.classList.remove("active"));
      b.classList.add("active");
      render();
    });
  });
}

/* ---- render list ---- */
function render(){
  const q = searchEl.value.trim().toLowerCase();
  const filtered = ALL_NOTES.filter(n=>{
    const okType = activeFilter==="all" || n.type===activeFilter;
    const okSearch = !q || n.title.toLowerCase().includes(q);
    return okType && okSearch;
  });

  if(!filtered.length){
    listEl.innerHTML = `<p class="notes-empty">No notes match.</p>`;
    return;
  }

  listEl.innerHTML = filtered.map(n=>{
    const meta = [n.modified ? fmtDate(n.modified) : null, n.size].filter(Boolean).join("  ·  ");
    return `<button class="note" data-path="${n.path}" data-type="${n.type}" data-title="${escapeAttr(n.title)}">
      <span class="note-type ${n.type}">${n.type}</span>
      <span class="note-main">
        <span class="note-title">${escapeHtml(n.title)}</span>
        <span class="note-meta">${meta}</span>
      </span>
      <span class="note-arrow">→</span>
    </button>`;
  }).join("");

  listEl.querySelectorAll(".note").forEach(el=>{
    el.addEventListener("click",()=>openNote(el.dataset.path, el.dataset.type, el.dataset.title));
  });
}

/* ---- open a note in the viewer ---- */
async function openNote(path, type, title){
  vTitle.textContent = "~/notes/" + title;
  viewer.classList.add("open");
  viewer.setAttribute("aria-hidden","false");
  document.body.style.overflow="hidden";

  if(type==="pdf"){
    vBody.innerHTML = `<iframe src="${path}#view=FitH" title="${escapeAttr(title)}"></iframe>
      <p style="margin-top:16px;font-size:13px;color:var(--text-faint)">
      Trouble viewing? <a href="${path}" target="_blank" rel="noopener">Open PDF in new tab ↗</a></p>`;
    return;
  }

  // markdown
  vBody.innerHTML = `<p style="color:var(--text-faint)">loading…</p>`;
  try{
    const res = await fetch(path,{cache:"no-store"});
    const md = await res.text();
    vBody.innerHTML = window.marked ? marked.parse(md) : `<pre>${escapeHtml(md)}</pre>`;
    vBody.scrollTop = 0;
  }catch(e){
    vBody.innerHTML = `<p>Couldn't load this note. <a href="${path}" target="_blank">Open raw ↗</a></p>`;
  }
}

function closeViewer(){
  viewer.classList.remove("open");
  viewer.setAttribute("aria-hidden","true");
  document.body.style.overflow="";
  vBody.innerHTML="";
}
vClose.addEventListener("click",closeViewer);
viewer.addEventListener("click",e=>{ if(e.target===viewer) closeViewer(); });
document.addEventListener("keydown",e=>{ if(e.key==="Escape") closeViewer(); });

searchEl.addEventListener("input",render);

/* ---- helpers ---- */
function fmtDate(iso){
  try{ return new Date(iso).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}); }
  catch{ return ""; }
}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function escapeAttr(s){return escapeHtml(s).replace(/"/g,"&quot;");}

loadNotes();

/* ============================================================
   Projects loader — same pattern as notes, but reads a
   hand-edited projects.json (tags/desc can't be auto-scanned).
   Search + tag-chips filter the cards.
   ============================================================ */
let ALL_PROJECTS = [], projTag = "all";
const pGrid    = document.getElementById("projects-grid");
const pSearch  = document.getElementById("projects-search");
const pFilters = document.getElementById("projects-filters");

async function loadProjects(){
  try{
    const res = await fetch("projects.json", {cache:"no-store"});
    if(!res.ok) throw new Error("no projects.json");
    ALL_PROJECTS = (await res.json()).projects || [];
    buildProjFilters();
    renderProjects();
  }catch(e){
    pGrid.innerHTML = `<p class="notes-empty">No projects yet. Add one to <code>projects.json</code>.</p>`;
  }
}

/* tag chips, built from every tag that appears */
function buildProjFilters(){
  const tags = ["all", ...new Set(ALL_PROJECTS.flatMap(p => p.tags || []))];
  pFilters.innerHTML = tags.map(t =>
    `<button class="filter-btn ${t===projTag?"active":""}" data-tag="${escapeAttr(t)}">${escapeHtml(t)}</button>`
  ).join("");
  pFilters.querySelectorAll(".filter-btn").forEach(b=>{
    b.addEventListener("click",()=>{
      projTag = b.dataset.tag;
      pFilters.querySelectorAll(".filter-btn").forEach(x=>x.classList.remove("active"));
      b.classList.add("active");
      renderProjects();
    });
  });
}

function renderProjects(){
  const q = pSearch.value.trim().toLowerCase();
  const filtered = ALL_PROJECTS.filter(p=>{
    const tags = (p.tags || []).map(t => t.toLowerCase());
    const okTag = projTag === "all" || tags.includes(projTag.toLowerCase());
    const hay = [p.name, p.desc, ...(p.tags || [])].join(" ").toLowerCase();
    return okTag && (!q || hay.includes(q));   // search hits tags, name, or desc
  });

  if(!filtered.length){ pGrid.innerHTML = `<p class="notes-empty">No projects match.</p>`; return; }

  pGrid.innerHTML = filtered.map(p=>{
    const idx   = String(ALL_PROJECTS.indexOf(p)+1).padStart(2,"0"); // stable number
    const tags  = (p.tags || []).map(escapeHtml).join('<span class="tag-sep">·</span>');
    const links = (p.links || []).map(l =>
      `<a href="${escapeAttr(l.url)}" target="_blank" rel="noopener">${escapeHtml(l.label)}</a>`).join("");
    return `<article class="project">
      <div class="project-top"><span class="project-idx">${idx}</span><span class="project-tags">${tags}</span></div>
      <h3 class="project-name">${escapeHtml(p.name)}</h3>
      <p class="project-desc">${escapeHtml(p.desc || "")}</p>
      <div class="project-links">${links}</div>
    </article>`;
  }).join("");
}

pSearch.addEventListener("input", renderProjects);
loadProjects();
